<!DOCTYPE html>
<html>
<head>
    <title>IT Support Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { bg-color: #f2f2f2; font-weight: bold; }
        .header { text-align: center; margin-bottom: 30px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: right; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h2>IT Support Hub - Operational Intelligence Report</h2>
        <p>Generated on: {{ now()->format('d M Y, h:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Staff</th>
                <th>Category</th>
                <th>Subject</th>
                <th>Raised At</th>
                <th>Solved At</th>
                <th>Time Spent</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($tickets as $ticket)
            @php
                $s = $ticket->total_seconds_spent;
                $hh = floor($s / 3600);
                $mm = floor(($s % 3600) / 60);
                if ($s > 0 && $s < 60) $mm = 1;
            @endphp
            <tr>
                <td>#{{ str_pad($ticket->id, 4, '0', STR_PAD_LEFT) }}</td>
                <td>{{ $ticket->staff->name }}</td>
                <td>{{ $ticket->category }}</td>
                <td>{{ $ticket->subject }}</td>
                <td>{{ $ticket->created_at->format('d/m/y h:i A') }}</td>
                <td>{{ $ticket->completed_at ? $ticket->completed_at->format('d/m/y h:i A') : 'N/A' }}</td>
                <td>{{ $hh }}h {{ $mm }}m</td>
                <td>{{ $ticket->status }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Page generated by IT Support System
    </div>
</body>
</html>
